name: Damage Calculation Test

on:
  push:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v10.14.2
      uses: actions/setup-node@v1
      with:
        node-version: '10.14.2'
        
    - run: yarn install
    - name: Install JUnit covrerage reporter
      run: yarn add --dev jest-junit
    - name: Run tests with JUnit as reporter
      run: npx jest --ci --runInBand --reporters=default --reporters=jest-junit
      env:
        JEST_JUNIT_OUTPUT_DIR: "./junit/test-reselts.xml"
    - uses: actions/upload-artifact@v2
      with:
        path: ./junit/test-results.xml
      if: always()
